# Generated by Django 5.0.4 on 2024-10-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beheerder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('feedback_field', models.TextField(max_length=600)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verantwoording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_1', models.CharField(max_length=100)),
                ('feedback_1_niveaus', models.CharField(max_length=100)),
                ('feedback_2', models.CharField(max_length=100)),
                ('feedback_2_niveaus', models.CharField(max_length=100)),
                ('feedback_3', models.CharField(max_length=100)),
                ('feedback_3_niveaus', models.CharField(max_length=100)),
                ('beoordelaar_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verantwoording_beoordelaar_1', to=settings.AUTH_USER_MODEL)),
                ('beoordelaar_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verantwoording_beoordelaar_2', to=settings.AUTH_USER_MODEL)),
                ('beoordelaar_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verantwoording_beoordelaar_3', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verantwoording_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
