# Generated by Django 5.0.4 on 2024-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verantwoording',
            name='verantwoording',
            field=models.CharField(default='default-value', max_length=600),
            preserve_default=False,
        ),
    ]
